### ISSUE TITLE
Confint.gam doesn't seem to like by variables

### ISSUE THREAD

**Issue by tamas-ferenci** [gavinsimpson/gratia#105]
Consider the following minimal reproducible example:

```r
library(mgcv)
library(ggplot2)

dat <- gamSim(1, n = 500, dist = "normal", scale = 2)
dat$byvar <- as.factor(sample(LETTERS[1:2], nrow(dat), replace = TRUE))
mod <- gam(y ~ s(x0, by = byvar) + byvar, data = dat)

ci <- confint(mod, parm = "x0", type = "confidence", partial_match = TRUE, shift = TRUE)
ggplot(ci, aes(x = x0, y = est, color = byvar)) + geom_line() + lims(x = c(0, 1), y = c(6, 9))

predgrid <- expand.grid(x0 = seq(0, 1, 0.01), byvar = LETTERS[1:2])
predgrid$pred <- predict(mod, predgrid)
ggplot(predgrid, aes(x = x0, y = pred, color = byvar)) + geom_line() + lims(x = c(0, 1), y = c(6, 9))
```

It seems as if the constant is only added to one of the groups...

**Comment by gavinsimpson** [comment]
This is technically-speaking working as documented; it adds the constant (intercept) term to the predictions, not any other terms in the model. The intent was to allow comparison of the smooths on a scale that is closer to the response scale, not to exactly reproduce the fitted response. In other words the intent wasn't to show the estimate group means plus the groups-specific smooths but solely to compare the group-specific smooths.

I could modify the function to include the coefs associated with the `by` variable but doing so would change the intention and shift the focus to a comparison of mean_j + f_j(x_i), when I rather thought the comparison should be on f_j(x_i).

**Comment by tamas-ferenci** [comment]
I see your point, thank you very much! I also understand why you don't want to change the already existing function, in that case would it be feasible to introduce a new function for that end? I see no other way to produce confidence intervals around the predicted values for a model that has `by` variables.

**Comment by gavinsimpson** [comment]
`confint()` is a bit of an oddity; it's old now and had to conform to base R's `confit()` generic. It was also around because `evaluate_smooth()` didn't add confidence bands. Whether and how to update this function is something I can think more about once I get some other functionality added, namely `smooth_estimates()` as the replacement for `evaluate_smooth()`.

One option for doing this would be to modify `compare_smooths()` such that in the single model case you could have it compare `by` smooths and then we could have an argument that would add on the relevant model terms to get the smooths on a comparable scale.

A problem with doing what you want more generically is that what you want only works for simple models with a single factor. Consider a model `y ~ f1 + f2 + s(x, by = f2)`. The intercept in that case would represent observations in the reference levels of both factors `f1` and `f2`, but you wouldn't necessarily want to centre smooths about those combinations. As you move away from very simple models then, providing simple interfaces for these kinds of things gets complicated and the best solution is often to create a data slice for the covariates of interest (`f2` and `x` in the above example) while setting `f1` (or other covariates) to representative values, before predicting response values for rows in the data slice, which one then plots.

There may be better options along the lines of {emmeans} but that seems quite complex to replicate, so this is for much later on in the development cycle of {gratia}. {emmeans} may already do what you want for example...?

**Comment by tamas-ferenci** [comment]
Thanks for the detailed answer! What I aimed is much less ambitious: simply a replacement of `mgcv::predict` that would provide confidence interval for the exact covariate combination that is used by the `predict` to give the prediction. (Better CI than the +/- 2 SE that I could obtain from the ordinary `predict` of `mgcv`).

**Comment by gavinsimpson** [comment]
More and more I see the virtue in having a `fitted_values()` or similar that would generate fitted values over the ranges of the covariates in the data or for some user-supplied values. I need this for my own work too. I'll start a new issue for that

**Comment by gavinsimpson** [comment]
LOL; I already did this following our conversation in #112
