### ISSUE TITLE
Strange behaviour of newdata in confint.gam

### ISSUE THREAD

**Issue by tamas-ferenci** [gavinsimpson/gratia#112]
Consider the following:

```
dat <- gamSim(1, n = 500, dist = "normal", scale = 2)
mod <- gam(y ~ s(x0) + s(x1), data = dat)
confint(mod, parm = "s(x0)", newdata = data.frame(x0 = seq(0, 1, 0.1)))
```

It is already a bit strange that this code runs: `x1` is not specified in `newdata` (what is its assumed value?); in contrast, `predict(mod, newdata = data.frame(x0 = seq(0, 1, 0.1)))` fails.

But the really strange thing is the following:

```
confint(mod, parm = "s(x0)", newdata = data.frame(x0 = seq(0, 1, 0.1)))
confint(mod, parm = "s(x0)", newdata = data.frame(x0 = seq(0, 1, 0.1), x1 = 0))
confint(mod, parm = "s(x0)", newdata = data.frame(x0 = seq(0, 1, 0.1), x1 = 1))
```

Results are exactly the same, i.e., it seems that `confint` disregards what is specified in `newdata`.

**Comment by gavinsimpson** [comment]
`mod` is *additive*, the values of `x1` don't affect `s(x0)`. As we're considering only the smooth f(x_0) and not anything else in the model, we can and do ignore `x1` as it's not needed to evaluate the smooth.

`predict()` will fail, but internally I'm not using `predict`. The code is a bit messy (because of silly design decisions which I've now rectified in `smooth_estimates()`), but if you look in `evaluate_1d_smooth()` in `evaluate_smooth.R` at [Line 197](https://github.com/gavinsimpson/gratia/blob/master/R/evaluate_smooth.R#L197) in the middle of that code you'll see a call to `spline_values()` ([L281](https://github.com/gavinsimpson/gratia/blob/master/R/evaluate_smooth.R#L281)), which is defined later in the file, and in there you'll see a call to `PredictMat()` ([L644](https://github.com/gavinsimpson/gratia/blob/master/R/evaluate_smooth.R#L644)) and that returns the prediction matrix for the specified smooth. As long as `newdata` contains what is needed for `PredictMat()` to evaluate the smooth in a Xp matrix sense then all is good.

`confint()` isn't ignoring what's in `newdata` it is using what it needs:

```r
confint(mod, parm = "s(x0)", newdata = data.frame(x0 = seq(0, 1, 0.1)))
```

returns

```
# A tibble: 11 x 8
   smooth by_variable    x0    est    se  crit   lower  upper
   <chr>  <fct>       <dbl>  <dbl> <dbl> <dbl>   <dbl>  <dbl>
 1 s(x0)  NA            0   -0.602 0.485  1.96 -1.55    0.348
 2 s(x0)  NA            0.1 -0.230 0.300  1.96 -0.818   0.359
 3 s(x0)  NA            0.2  0.126 0.252  1.96 -0.369   0.620
 4 s(x0)  NA            0.3  0.449 0.248  1.96 -0.0373  0.936
 5 s(x0)  NA            0.4  0.691 0.250  1.96  0.201   1.18 
 6 s(x0)  NA            0.5  0.767 0.255  1.96  0.266   1.27 
 7 s(x0)  NA            0.6  0.620 0.262  1.96  0.107   1.13 
 8 s(x0)  NA            0.7  0.232 0.264  1.96 -0.285   0.750
 9 s(x0)  NA            0.8 -0.403 0.271  1.96 -0.934   0.128
10 s(x0)  NA            0.9 -1.26  0.329  1.96 -1.90   -0.614
11 s(x0)  NA            1   -2.23  0.521  1.96 -3.25   -1.21 
```

which is the smooth and confidence interval evaluated at the requested 11 values of `x0`, likewise for

```r
confint(mod, parm = "s(x0)", newdata = data.frame(x0 = seq(0, 1, 0.1), x1 = 1))
```
yielding
```
# A tibble: 11 x 8
   smooth by_variable    x0    est    se  crit   lower  upper
   <chr>  <fct>       <dbl>  <dbl> <dbl> <dbl>   <dbl>  <dbl>
 1 s(x0)  NA            0   -0.602 0.485  1.96 -1.55    0.348
 2 s(x0)  NA            0.1 -0.230 0.300  1.96 -0.818   0.359
 3 s(x0)  NA            0.2  0.126 0.252  1.96 -0.369   0.620
 4 s(x0)  NA            0.3  0.449 0.248  1.96 -0.0373  0.936
 5 s(x0)  NA            0.4  0.691 0.250  1.96  0.201   1.18 
 6 s(x0)  NA            0.5  0.767 0.255  1.96  0.266   1.27 
 7 s(x0)  NA            0.6  0.620 0.262  1.96  0.107   1.13 
 8 s(x0)  NA            0.7  0.232 0.264  1.96 -0.285   0.750
 9 s(x0)  NA            0.8 -0.403 0.271  1.96 -0.934   0.128
10 s(x0)  NA            0.9 -1.26  0.329  1.96 -1.90   -0.614
11 s(x0)  NA            1   -2.23  0.521  1.96 -3.25   -1.21 
```

**Comment by tamas-ferenci** [comment]
Thanks Gavin for the detailed explanation! I was actually looking for a drop-in replacement of the original `predict` so that I can obtain the same predictions but with good confidence intervals for the prediction. `gratia::confint.gam` seemed to be a logical choice (and the `newdata` argument looked very promising), but I now see that I misunderstood it. Nevertheless, is it possible to achieve this - obtaining predictions and CIs for them - with gratia...?

**Comment by gavinsimpson** [comment]
Ah, I see. I just added `fitted_values()` which I think does what you want:

```r
> fitted_values(b_pois, scale = "response")                          
# A tibble: 500 x 8
      x0    x1     x2     x3 fitted     se lower upper
   <dbl> <dbl>  <dbl>  <dbl>  <dbl>  <dbl> <dbl> <dbl>
 1 0.915 0.137 0.848  0.0539   1.78 0.0913  1.49  2.13
 2 0.937 0.177 0.0627 0.955    2.25 0.0867  1.90  2.66
 3 0.286 0.520 0.820  0.0256   3.00 0.0865  2.54  3.56
 4 0.830 0.811 0.539  0.921    7.01 0.0759  6.04  8.13
 5 0.642 0.115 0.499  0.367    3.60 0.0756  3.10  4.17
 6 0.519 0.893 0.0222 0.698    4.40 0.110   3.55  5.46
 7 0.737 0.575 0.554  0.569    4.91 0.0701  4.28  5.63
 8 0.135 0.147 0.720  0.284    2.40 0.0781  2.06  2.80
 9 0.657 0.903 0.236  0.0114  24.9  0.0627 22.0  28.1 
10 0.705 0.253 0.812  0.421    2.46 0.0807  2.10  2.89
# … with 490 more rows
```

which can take new data values via its `data` argument. Additional arguments to `predict.gam` can be passed via `...`, but note that `newdata`, `type` and `se.fit` are already specified and thus can't be changed/passed yourself.

**Comment by gavinsimpson** [comment]
Note that this only works for models with families up to and including those covered by `extended.family`; none of the `general.family` model types are handled yet (this includes all the location scale families, `mvn()`, `multinom()`, etc.) but things like `betar()`, `nb()`, `tw()` work just fine, as do the basic R families that {mgcv} understands.

**Comment by gavinsimpson** [comment]
Let me know if this isn't what you had in mind?

**Comment by tamas-ferenci** [comment]
Perfect, thank you very much, Gavin!
