### ISSUE TITLE
Controlling colour for fitted smooths and confidence bands

### ISSUE THREAD

**Issue by isabellaghement** [gavinsimpson/gratia#128]
Hi Gavin, 

I am trying to control colour for plots of fitted smooths and confidence bands produced by a GAMM model and it doesn't seem to be that easy to do so with gratia's draw().  The draw() function returns patchwork objects (rather than ggplot ones), which makes it difficult to control the things I mentioned.  

My GAMM model looks like this: 

```

hgdat <- import("Data\\hgdat.xlsx")

str(hgdat)   # str() 

library(mgcv)

m5rfs <- gam(Biomass ~ Region + s(Time, by = Region, m = 2) + 
               s(Time, Site, bs = "fs", m = 2),
             method = "REML", 
             data = hgdat5)
```
I loaded the dataset hgdat so you can reproduce the above example.  

[hgdat.xlsx](https://github.com/gavinsimpson/gratia/files/7973967/hgdat.xlsx)

On Twitter, I received suggestions for achieving colour control which inspired three possible solutions.

**Solution No. 1:**

The first suggestion for a solution came from Dilsher Dhillon (https://twitter.com/dhillon_stats/status/1488234181566029831) - it works but is convoluted.  It involves recovering the plotting dataframe back from the ggplot via a ggproto object:

```
 plot <- draw(m5rfs, select = "s(Time):RegionSVI")
  
 data_for_plot_1 <- ggplot2::ggplot_build(plot)$data[[1]]
 data_for_plot_2 <- ggplot2::ggplot_build(plot)$data[[2]]
  
  data_for_plot_2 %>% 
    ggplot(aes(x = x, y = y)) +
    geom_line(colour = "red", size = 1) + 
    geom_ribbon(data = data_for_plot_1, 
                aes(x = x, ymin = ymin, ymax = ymax), 
                fill = "blue", alpha = 0.2, 
                inherit.aes = FALSE) 
```

It produces this plot: 

![image](https://user-images.githubusercontent.com/57458528/151867612-51399695-c575-465a-ae8c-2fcfc9522cef.png)

which seems to match what draw() produces for the same smooth:

![image](https://user-images.githubusercontent.com/57458528/151867745-b088c73d-1442-45d6-b15f-c6a910c27085.png)

But I don't like this first solution because it is clunky and am nervous about whether or not I extracted the values of the fitted curve and the upper/lower confidence bands correctly from the ggproto object.  They seemed to be nested in different parts of this model.

**Solution No. 2:**

The second solution suggested by Brenton Wiernik on Twitter (https://twitter.com/bmwiernik/status/1488239771960983553) involves gratia's evaluate_smooths() but R throws an error when I apply this function to my model - not sure why:

```
library(gratia)
load_mgcv()

smooth_dat <- evaluate_smooth(m5rfs, smooth = "s(Time):RegionSVI")

ggplot(smooth_dat) +
  aes(x = x2) +
  geom_ribbon(
    aes(ymin = est - 1.96 * se, ymax = est + 1.96 * se),
    fill = see::material_colors("blue"), alpha = .5
  ) +
  geom_line(
    aes(y = est),
    color = see::material_colors("blue")
  ) +
  geom_point(
    data = dat,
    y = min(smooth_dat$est - 1.96 * smooth_dat$se) - .1,
    shape = "|", color = see::material_colors("blue"), size = 3, alpha = .4
  ) +
  see::theme_modern()
```
The error thrown by R is this: 

![image](https://user-images.githubusercontent.com/57458528/151868222-4dd0743e-b482-4372-9e8e-661a95ff0c13.png)

If the draw() function were to return the object **sm_plts** BEFORE this object is fed to patchwork's wrap_plots(), maybe it would be easier to control colours (?).  Not sure...

Alternatively, if the function draw.evaluated_1d_smooth() and others like it were to include explicit arguments for controlling the colour of the fitted curves and confidence bands, that would give the user the colour control they need. Something like this: 

```
## plot the confidence interval
  plt <- plt + geom_ribbon(mapping = aes_string(ymin = "lower",
                                                ymax = "upper"),
                           alpha = 0.3, 
                           fill = fill_confidence_band) +
    geom_line(colour = colour_fitted_curve)
```

I tried "hacking"  the gratia code by defining my own modified version of draw.evaluated_1d_smooth() as above, but then, when I load gratia, R doesn't find all sorts of helper functions it needs such as add_constant(), etc., and I have to hunt them down and load them from github which is a pain.  Not sure why these helper functions remain hidden to R after loading the package in the current session? (Brenton clarified that these functions could be accessed with gratia:::add_constant(), etc.) 

**Solution No. 3:**

With Brenton's and your help on Twitter, I found this third solution: 

```
# evaluate first two smooths 
sm_eval_1_2 <- smooth_estimates(m5rfs, smooth = smooths(m5rfs)[1:2])
sm_eval_1_2

# add 95% confidence bands to the evaluated smooths
ci_sm_eval_1_2 <- gratia:::add_confint(sm_eval_1_2, coverage = 0.95)

# plot fitted smooths and 95% confidence bands
library(ggplot2)
library(magrittr)
theme_set(theme_bw())

ci_sm_eval_1_2 %>% 
  ggplot(aes(x = Time, y = est)) + 
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci, 
                  colour = smooth, fill = smooth), alpha = 0.2) +
  geom_line(aes(colour = smooth), size = 1)  + 
  facet_wrap( ~ smooth)

``` 
which produces this nicely coloured plot of the fixed effects smooths:

![image](https://user-images.githubusercontent.com/57458528/151907300-8e7faf15-4743-4307-b39e-52fc4a292ea9.png)

With this third solution, I can even get confidence bands for the random factor smooths (something that draw() doesn't seem to report), as well as properly labelled random factor smooths:  

```
# extract the fitted random smooths of Time by Site 
# encompassed by the random factor smooth s(Time,Site)
sm_eval_3 <- smooth_estimates(m5rfs, smooth = smooths(model)[3])
sm_eval_3

# add confidence bands to the fitted random smooths of Time by Site 
ci_sm_eval_3 <- gratia:::add_confint(sm_eval_3, coverage = ci_level)
ci_sm_eval_3

# plot the fitted random smooths of Time by Site and the 95% confidence bands 
ci_sm_eval_3 %>% 
  ggplot(aes(x = Time, y = est, group = Site)) + 
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci, 
                  colour = Site, fill = Site), alpha = 0.2) +
  geom_line(aes(colour = Site), size = 1) + 
  # facet_wrap( ~ Site) +
  facet_grid( ~ Site, labeller = label_both) + 
  ylab("Partial Effect") + 
  ggeasy::easy_remove_legend() + 
  ggtitle(paste0("Random Factor Smooth: ", smooths(model)[3]))
```

The resulting plot for the third solution looks like so: 

![image](https://user-images.githubusercontent.com/57458528/151907809-4ed8060e-e87a-4885-899a-77f54851fa51.png)

For this third solution, I am not 100% sure I am using gratia:::add_confint() correctly.  Gavin, in your Github code, it appears that this function is applied row by row to the underlying data used to compute the confidence bands() using the rowwise() function from dplyr:

![add_confint](https://user-images.githubusercontent.com/57458528/151908116-4fd41b4a-ad7c-48d8-84d7-9f1e703fd7fa.jpg)

But the way I applied it above does not seem to require a row-wise application of the function (neither do I use any ungrouping, etc.).   

I rather like this third solution for the flexibility in offers in customizing the resulting plots and I hope my understanding of how gratia:::add_confint() is supposed to work is correct (?).  In particular, is this function computing the correct confidence bands for the random factor smooths the way I applied it?  Is it OK to use it without using rowwise() first and without worrying about ungrouping?  

Any advice on how to sort out this issue would be much appreciated. Thanks very much, Gavin!

**Comment by gavinsimpson** [comment]
Solution 1 is OK in the absence of any other way to achieve what you want.

Solution 2 is close, just don't use `evaluate_smooth()` now, or rather I have deprecated `evaluate_smooth()` because it was too complicated to support more complex models without writing spaghetti code and breaking previously working examples. `smooth_estimates()` should be used now, with a GH version 0.6.9xxx or later. I'm reasonably sure that's why this solution is failing for your smooth (although it should work for factor by smooths, you just can't refer to a single smooth like that IIRC you need to use `smooth = "Time"` or something like that to get all those by smooths. This is the main mistake &mdash; how I handled factor by smooths &mdash; that I corrected with `smooth_estimates()` and why `evaluate_smooth()` will be superseded as of version 0.7.0.

Solution 3 is what I would do if I wanted to have control over what is plotted and how, except `add_confint()` is exported from {gratia} so you should reinstall from GH.

In `draw.gam`, which is working on potentially many smooths, I return the output of `smooth_estimates()` in a nested format, where the result is a data frame but with only a single row per smooth. Each of those rows contains a nested data frame

```r
r$> smooth_estimates(m, unnest = FALSE)                                             
# A tibble: 4 × 4
  smooth type  by    data              
  <chr>  <chr> <chr> <list>            
1 s(x0)  TPRS  NA    <tibble [100 × 3]>
2 s(x1)  TPRS  NA    <tibble [100 × 3]>
3 s(x2)  TPRS  NA    <tibble [100 × 3]>
4 s(x3)  TPRS  NA    <tibble [100 × 3]>
```

To see what's in one of those rows, we can extract it and `tidyr::unnest()` it

```r
r$> sm <- smooth_estimates(m, unnest = FALSE)                                       
r$> sm <- sm[1, ]                                                                   
r$> sm                                                                              
# A tibble: 1 × 4
  smooth type  by    data              
  <chr>  <chr> <chr> <list>            
1 s(x0)  TPRS  NA    <tibble [100 × 3]>
r$> unnest(sm, cols = data)                                                         
# A tibble: 100 × 6
   smooth type  by       est    se      x0
   <chr>  <chr> <chr>  <dbl> <dbl>   <dbl>
 1 s(x0)  TPRS  NA    -0.974 0.352 0.00162
 2 s(x0)  TPRS  NA    -0.918 0.332 0.0117 
 3 s(x0)  TPRS  NA    -0.862 0.312 0.0217 
 4 s(x0)  TPRS  NA    -0.805 0.294 0.0318 
 5 s(x0)  TPRS  NA    -0.750 0.277 0.0418 
 6 s(x0)  TPRS  NA    -0.694 0.262 0.0519 
 7 s(x0)  TPRS  NA    -0.638 0.249 0.0620 
 8 s(x0)  TPRS  NA    -0.583 0.238 0.0720 
 9 s(x0)  TPRS  NA    -0.529 0.228 0.0821 
10 s(x0)  TPRS  NA    -0.475 0.220 0.0921 
```

and if you were to `unnest()` the whole thing, you'd get

```r
r$> smooth_estimates(m, unnest = FALSE) %>% 
      unnest(cols = data)                                                           
# A tibble: 400 × 9
   smooth type  by       est    se      x0    x1    x2    x3
   <chr>  <chr> <chr>  <dbl> <dbl>   <dbl> <dbl> <dbl> <dbl>
 1 s(x0)  TPRS  NA    -0.974 0.352 0.00162    NA    NA    NA
 2 s(x0)  TPRS  NA    -0.918 0.332 0.0117     NA    NA    NA
 3 s(x0)  TPRS  NA    -0.862 0.312 0.0217     NA    NA    NA
 4 s(x0)  TPRS  NA    -0.805 0.294 0.0318     NA    NA    NA
 5 s(x0)  TPRS  NA    -0.750 0.277 0.0418     NA    NA    NA
 6 s(x0)  TPRS  NA    -0.694 0.262 0.0519     NA    NA    NA
 7 s(x0)  TPRS  NA    -0.638 0.249 0.0620     NA    NA    NA
 8 s(x0)  TPRS  NA    -0.583 0.238 0.0720     NA    NA    NA
 9 s(x0)  TPRS  NA    -0.529 0.228 0.0821     NA    NA    NA
10 s(x0)  TPRS  NA    -0.475 0.220 0.0921     NA    NA    NA
# … with 390 more rows
```

Because I want to apply code to the rows of

```r
r$> smooth_estimates(m, unnest = FALSE)                                             
# A tibble: 4 × 4
  smooth type  by    data              
  <chr>  <chr> <chr> <list>            
1 s(x0)  TPRS  NA    <tibble [100 × 3]>
2 s(x1)  TPRS  NA    <tibble [100 × 3]>
3 s(x2)  TPRS  NA    <tibble [100 × 3]>
4 s(x3)  TPRS  NA    <tibble [100 × 3]>
```

I can't call `add_confint()` on that object because it doesn't have the requisite columns while in nested form

```r
r$> smooth_estimates(m, unnest = FALSE) %>% add_confint()                           
Error in add_confint.smooth_estimates(.) : 
  'object' does not contain one or both of 'est', 'se'.
  Did you use `smooth_estimates(..., unnest = FALSE)`?
```

You'd have been a lot better off looking at the definition for `add_confint()` (actually `gratia:::add_confint.smooth_estimates()` in this case):

```r
r$> sm <- smooth_estimates(m)                                                       
r$> class(sm)                                                                       
[1] "smooth_estimates" "tbl_df"           "tbl"              "data.frame"      
r$> methods("add_confint")                                                          
[1] add_confint.default          add_confint.smooth_estimates
see '?methods' for accessing help and source code
r$> getAnywhere("add_confint.smooth_estimates")                                     
A single object matching ‘add_confint.smooth_estimates’ was found
It was found in the following places
  package:gratia
  registered S3 method for add_confint from namespace gratia
  namespace:gratia
with value

function(object, coverage = 0.95, ...) {
    # check if this is nested
    nms <- names(object)

    if (!all(c("est", "se") %in% nms)) {
        stop("'object' does not contain one or both of ",
             "'est', 'se'.",
             "\n  Did you use `smooth_estimates(..., unnest = FALSE)`?")
    }

    ## compute the critical value
    crit <- coverage_normal(coverage)

    ## add the frequentist confidence interval
    object <- mutate(object,
                     lower_ci = .data$est - (crit * .data$se),
                     upper_ci = .data$est + (crit * .data$se))

    ## return
    object
}
<environment: namespace:gratia>
```

as that would be a lot easier to understand.

**Comment by gavinsimpson** [comment]
Anyway, if you are using version 0.6.9800 or later of {gratia} (i.e. from the time of writing) you can now change a few elements of the plot

```r
library("gratia")
load_mgcv()
# simulate some data
df <- data_sim("eg1", seed = 21)
# fit a GAM
m <- gam(y ~ s(x0) + s(x1) + s(x2) + s(x3), data = df, method = "REML")
# plot the smooths changing some elements of the plot
draw(m, ci_col = "goldenrod", smooth_col = "hotpink", ci_alpha = 0.4)
```

![draw-gam-custom-colours](https://user-images.githubusercontent.com/514696/151963551-35ca14ab-591e-41b1-af3e-3effc4e1bb91.png)

Similar stuff works for `smooth_estimates()` objects too

```r
sm <- smooth_estimates(m, smooth = c("s(x1)", "s(x2)"))
draw(sm, ci_col = "goldenrod", smooth_col = "hotpink", ci_alpha = 0.4)
```

![draw-gam-custom-colour-2](https://user-images.githubusercontent.com/514696/151963833-ec020aee-25fd-4461-bda5-0c435a729bc8.png)

If you want to do facets, and have colours mapped to factor levels/panels then you have to do all this via `smooth_estimates()` and plot however you want them to look.

It's just not possible to allow the sort of customization that users might like when you could be plotting panels that contain multiple lines ('fs' smooths), a QQ plot of the ranefs ('re' smooths), 2d surfaces, 3 or 4d smooth (which I plan to support via `facet_wrap()` and `facet_grid()` respectively producing a single plot for the smooth [with multiple facets]), and parametric terms, let alone fancier smooths like MRFs and splines on the sphere (when I get around to supporting those).

@isabellaghement You asked about adding partial residuals to your custom plot, IIRC on Twitter. This gets a lot more complex, because the partial residuals apply to the original data and not the data created to draw the smooth(s). `draw.gam()` handles this is a hacky way to nest more data frames into each row of the nested output from `smooth_estimates` (same for the rugs).

There is an `add_partial_residuals()` but you have to be very careful with this as you can get it to do silly things if you ask it to: it literally just extracts the residuals for each row in the original data and adds them to the tibble it was passed. I need to check if this works with factor by smooths - I think it does as I think I'm using it internally to add partial residuals to factor by smooths.
