### ISSUE TITLE
`draw` fails for models with no smoothing 

### ISSUE THREAD

**Issue by Nelson-Gon** [gavinsimpson/gratia#142]
Hi,

Awesome package, continuing from my discussion from Twitter. I have tried the following and found that `draw` fails 

```
library(gratia)
library(mgcv)
dat <- data_sim("eg4", n = 400, seed = 42)
b <- gam(y ~ x0 + x1 + x2 , data = dat, method = "REML")
appraise(b)
draw(b, parametric = TRUE)
```

It fails with 

>Unable to draw any of the model terms.

I am using `gratia` ‘0.6.0’.

**EDIT**

I have upgraded to `0.7.0` and now have the following error 

>Error: Problem with `mutate()` column `data`.
i `data = list(add_confint(.data$data, coverage = ci_level))`.
x Column `data` not found in `.data`

A traceback

```
+-<error/dplyr:::mutate_error>
| Problem with `mutate()` column `data`.
| i `data = list(add_confint(.data$data, coverage = ci_level))`.
| x Column `data` not found in `.data`
\-<error/rlang_error_data_pronoun_not_found>
  Column `data` not found in `.data`
Backtrace:
  1. gratia::draw(b, parametric = TRUE)
 14. rlang:::abort_data_pronoun(x)

```

Thank you,

NelsonGon

**Comment by gavinsimpson** [comment]
Confirmed; thanks @Nelson-Gon. I'll see where the issue is...

**Comment by gavinsimpson** [comment]
This was caused by a couple of issues with the ordering of code in `draw.gam()` and a potential problem in `predict.gam()` where if one passes `exclude = character(0)` (which arises when `smooths()` returns such a thing for a model with no smooths...), `predict.gam()` doesn't return *any* columns in the `fit` or `se.fit` arrays.

The ordering issues are fixed and the `exclude` problem is now worked around...
