### ISSUE TITLE
smooth_estimates() is not generating estimates for all integer years

### ISSUE THREAD

**Issue by JuanWang814** [gavinsimpson/gratia#180]
I am trying to produce my own 3-dimensional plots based on the estimates generated by `smooth_estimates()`.
 
I got `year` in the three way interaction and it has 5 continuous integer levels (`2011:2015`):
```
library(tidyverse)
library(gamm4)
library(gratia)

df <- data_sim("eg2", n = 50, dist = "normal", scale = 1, seed = 2)
df <- mutate(df, year = c(rep(2011:2015, 10)))

dfm <- gamm4(y ~ t2(x, z, year), data = df)

se <- smooth_estimates(dfm)
```

`smooth_estimates()` evenly generated **100** unique levels between `2011` and `2015` but these levels don't contain integer `2012`, `2013`, `2014`. 
```
> unique(se$year)
  [1] 2011.000 2011.040 2011.081 2011.121 2011.162 2011.202 2011.242 2011.283 2011.323 2011.364 2011.404
 [12] 2011.444 2011.485 2011.525 2011.566 2011.606 2011.646 2011.687 2011.727 2011.768 2011.808 2011.848
 [23] 2011.889 2011.929 2011.970 2012.010 2012.051 2012.091 2012.131 2012.172 2012.212 2012.253 2012.293
 [34] 2012.333 2012.374 2012.414 2012.455 2012.495 2012.535 2012.576 2012.616 2012.657 2012.697 2012.737
 [45] 2012.778 2012.818 2012.859 2012.899 2012.939 2012.980 2013.020 2013.061 2013.101 2013.141 2013.182
 [56] 2013.222 2013.263 2013.303 2013.343 2013.384 2013.424 2013.465 2013.505 2013.545 2013.586 2013.626
 [67] 2013.667 2013.707 2013.747 2013.788 2013.828 2013.869 2013.909 2013.949 2013.990 2014.030 2014.071
 [78] 2014.111 2014.152 2014.192 2014.232 2014.273 2014.313 2014.354 2014.394 2014.434 2014.475 2014.515
 [89] 2014.556 2014.596 2014.636 2014.677 2014.717 2014.758 2014.798 2014.838 2014.879 2014.919 2014.960
[100] 2015.000
```
This isn't really an issue in 2d plotting but in 3d, I can't produce plots specifically for these three integer years as facets. 

I think the number of levels generated by `smooth_estimates()` needs a little tweak?

BTW I like this package.

**Comment by gavinsimpson** [comment]
> I think the number of levels generated by smooth_estimates() needs a little tweak?

No.

> `smooth_estimates()` evenly generated **100** unique levels between `2011` and `2015` but these levels don't contain integer `2012`, `2013`, `2014`.

This is by design; you fitted a model in which `year` is continuous and hence the only sensible default when evaluating a smooth is to spread the required number of values (to see or visualise the smooth function) evenly over the range of the covariate.

With only 5 values one could make a good argument to have treated `year` as a categorial variable and fitted a factor-smooth-interaction, either:

```r
df <- mutate(fyear = as.factor(year))
m <- gamm4(y ~ fyear + t2(x, z, by = fyear), data = df)
```

or

```r
df <- mutate(fyear = as.factor(year))
m <- gamm4(y ~ t2(x, z, fyear, bs = c("cr", "cr", "re")), data = df, full = TRUE)
```

But if you want to model `year` as a smooth function then the other alternative is to tell `smooth_estimates()` where you want to evaluate the smooth. Using the development version of {gratia} on GitHub, you should be able to do

```r
# 1. create the values you want to evaluate the smooth at
ds <- data_slice(dfm, x = evenly(x), z = evenly(z), year = unique(year))

# 2. evaluate the smooth
sm <- smooth_estimates(dfm, data = ds)

# 3. plot
library("ggplot2")
lims <- c(-1, 1) * max(abs(sm[["est"]]))
sm %>%
  ggplot(aes(x = x, y = z)) +
    geom_raster(aes(fill = est)) +
    geom_contour(mapping = aes(z = est), colour = "black") +
    facet_wrap(~ year) +
    scale_fill_distiller(palette = "RdBu", type = "div") +
    expand_limits(fill = lims) +
    labs(fill = "Partial effect")
```

which gives:

![plot (2)](https://user-images.githubusercontent.com/514696/182094000-cb34ffb8-d4ea-45f6-a95e-2a57a2039320.png)

The only thing that needs the development version is the `data_slice()` (and `evenly()`) call. You could recreate this with your data using

```r
ds <- with(df, expand.grid(x = seq(min(x), max(x), length = 100),
                           z = seq(min(z), max(z), length = 100),
                           year = unique(year)))
```

the rest of the code in the block above remaining the same.

> BTW I like this package.

Thanks!
