### ISSUE TITLE
Plotting slices of a 2D smooth

### ISSUE THREAD

**Issue by fhui28** [gavinsimpson/gratia#182]
Sorry if this is a silly question for which there is already an workable answer. Is there a way to plot slices of a two-dimensional smooth in `gratia`? I can not seem to find a way of doing this in base `mgcv`, while it was not clear that the `gratia::data_slice` could slice through a covariate within a tensor-product smooth [say]. 

I also had a look at `mgcViz`, but they have a `plotSlice` function which can plot slices of multidimensional smooth provided the dimension exceeds 2.

The closest I can find which can do this is the `vis.pfr` function in the `refund` package for penalized functional regression, where if for a functional GAM [which is basically like a tensor product with a `by` argument], then you can plot slices by specifying the covariate values you want to slice at. Here is an example based on the help file of `refund::vispfr`.

```
data(DTI)
## only consider first visit and cases (no PASAT scores for controls)
DTI1 <- DTI[DTI$visit==1 & DTI$case==1,]
DTI2 <- DTI1[complete.cases(DTI1),]

## fit FGAM using FA measurements along corpus callosum as functional predictor with PASAT as response using 8 cubic B-splines for marginal bases with third order marginal difference penalties specifying gamma > 1 enforces more smoothing when using GCV to choose smoothing parameters
fit1 <- pfr(pasat ~ af(cca, k=c(8,8), m=list(c(2,3), c(2,3)), bs="ps"), method="ML", data = DTI2)

vis.pfr(fit1) # Perspective plots, very similar to vis.gam

vis.pfr(fit1, xval = 0.5) # Slice at cca = 0.5, and plot the smooth as a function of t

vis.pfr(fit1, tval = 0.2) # Slice at t = 0.2, and plot the smooth as a function of cca
```
 
Thanks heaps!

**Comment by gavinsimpson** [comment]
This should be doable @fhui28 . Will work up an example but might not be for a day or two more as I'm away at a conference just now.

**Comment by gavinsimpson** [comment]
Here's a couple of worked examples (that I'm going to base a vignette for the package on, so apologies if some of the below is overkill in terms of exposition).

The general idea thus far has been to provide the tools needed to allow familiar working within the tidyverse and ggplot2 ecosystems, rather than canned functions, so there's no `vis.gam` or `vis.pfr` alikes in gratia (yet).

`vis.gam` produces estimates of \hat{y} IIRC and I'm not sure exactly what `vis.pfr` produces (I should look at it in more detail), but with gratia we have two main options:

1. use `smooth_estimates()` to evaluate the estimated smooth `te(x,z)` say at some values `x` and fixed/constant `z`, or
2. use `fitted_values()` to get fitted values of the model at some values `x` and fixed/constant `z`, holding any other covariates in the model at representative values.

Given how easy it is to go from `smooth_estimates()` or `fitted_values()` to a plot I'm not sure how much more useful including a direct alternative to `vis.gam` or `vis.pfr` in {gratia} will be?

## Example

For this I'll use the bivariate data set from {mgcv} but fit a tensor product of `x` and `z`.

```r
library("mgcv")
library("gratia")
library("ggplot2")

# simulate data from the bivariate surface
df <- data_sim("eg2", n = 1000, scale = 0.25, seed = 2)

# fit the GAM
m <- gam(y ~ te(x,z), data = df, method = "REML")
```

### Using `smooth_estimates()`

Begin by creating a slice through the data space (you'll need the development version of {gratia} for this as it has the improved `data_slice()` and new `evenly()` helper function). If there were any other covariates in the model, they would be fixed here at the closest observation to the median (continuous covariates) or the modal level (factor covariates). We also create a label at this point for a nice axis label.

```r
# any covariate not mentioned in the `data_slice()` call gets set to a representative value
ds <- data_slice(m,
                 x = evenly(x, n = 100),
                 z = quantile(z, probs = 0.25))

z_val <- with(ds, round(quantile(z, probs = 0.25),2))
ylab <- bquote(hat(f)(x, .(z_val)))
```

Then we just evaluate the smooth at the desired values

```r
sm <- smooth_estimates(m, smooth = "te(x,z)", data = ds) |>
  add_confint()
```

and plot

```
sm |>
  ggplot(aes(x = x, y = est)) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci), alpha = 0.2) +
  geom_line() +
  labs(title = "Evaluation of smooth te(x,z) at fixed z",
       y = ylab)
```

<img src="https://user-images.githubusercontent.com/514696/186637966-426eeb05-d421-4f67-9b1b-46b06e9049e1.png" width=75%>

Note that unlike `vis.pfr`, the above interval is not the Marra and Wood (2012) interval. It doesn't include the uncertainty from the model constant term at the moment, but unless the smooth is very close to linear that shouldn't make too much difference.

This extends to multiple slices by asking for several discrete `z`

```r
ds2 <- data_slice(m, x = evenly(x, n = 100),
                  z = round(quantile(z, probs = c(0.25, 0.5, 0.75)), 2))

sm2 <- smooth_estimates(m, smooth = "te(x,z)", data = ds2) |>
  add_confint() |>
  mutate(fz = factor(z))

sm2 |>
  ggplot(aes(x = x, y = est, colour = fz, group = fz)) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci, fill = fz, colour = NULL),
              alpha = 0.2) +
  geom_line() +
  labs(title = "Evaluation of smooth te(x,z) at fixed z",
       y = expression(hat(f)(x,z)), colour = "z", fill = "z")
```

<img src="https://user-images.githubusercontent.com/514696/186638176-8f5f43aa-b0ff-4fe0-80fd-81f1327fcdfe.png" width=75%>

### Using `fitted_samples()`

If you want to evaluate the surface over `x` at fixed `z` conditional upon other values of other covariates (model predicted or fitted values) then `fitted_samples()` is a tidy wrapper to `predict.gam()`.

For single `z` we have

```r
fitted_values(m, data = ds) |> # default is response scale, not link
  ggplot(aes(x = x, y = fitted)) +
  geom_ribbon(aes(ymin = lower, ymax = upper), alpha = 0.2) +
  geom_line() +
  labs(title = "Fitted values from model",
       y = expression(hat(y)))
```

(where `ds` would already include representative values of the other covariates if there were any in the model, as `data_slice()` does that for you.)

And for the multiple `z` we have

```r
fitted_values(m, data = ds2) |>
  mutate(fz = factor(z)) |>
  ggplot(aes(x = x, y = fitted, colour = fz, group = fz)) +
  geom_ribbon(aes(ymin = lower, ymax = upper, fill = fz, colour = NULL),
              alpha = 0.2) +
  geom_line() +
  labs(title = "Fitted values from model",
       y = expression(hat(y)), colour = "z", fill = "z")
```

where the only difference here is that the model constant is included and it's uncertainty.

**Comment by fhui28** [comment]
That is awesome! Thank you so much @gavinsimpson! And yes I was looking for a `ggplot` driven approach rather than "canned recipes" anyway haha. Apologies for not recognizing earlier that this could have been done already using `smooth_estimates()` and `fitted_samples()`

Much appreciated!
