### ISSUE TITLE
difference_smooths() returns non-conformable arrays

### ISSUE THREAD

**Issue by Dallak** [gavinsimpson/gratia#188]
Dear Gavin,
Thank you for this great package. I has helped me a lot  in my work.

I'm trying to use the function `difference_smooths()` on one of my models that has this structure:

```
bam(val ~       x1x2 +
                       s(percent, bs= "cr", k=10) +
                       s(percent, bs= "cr", k=10, by=x1x2) +
                       s(percent, stim, bs="fs", m=1, k=10, by=x1x2)+
                       s(percent, stim, bs="fs", m=1, k=10)+
                       s(percent, word, bs="fs", m=1, k=10),   
                       data = kurt_gam_aa_ini,
                       AR.start=kurt_gam_aa_ini$start.event,
                       method = "fREML",
                       family = "scat",
                       nthread=8,
                       rho = kurt_ini__comp_aa_m1_roh)))
```

 but it returns this error:

```
Error in Xp[r1, ] - Xp[r2, ] : non-conformable arrays
```
Is there any advice or workaround to fix this?

I also tried using it with another model fitted using an older `mgcv` version (1.8-28), but it returns:

```
Error in 1:dk$nr[i] : NA/NaN argument
In addition: Warning message:
prediction from discrete bam models prior to 1.8-32 is deprecated, please refit 
```
Is there any solution for this other than refitting the model?

Your input is highly valued.

**Comment by gavinsimpson** [comment]
What was the `difference_smooths()` call that you used? What version of {gratia}?

**Comment by gavinsimpson** [comment]
That's a different error, and is because you are specifying only a single smooth (it would appear): namely the specific smooth of `percent` for the `voiced.d` level of the factor `x1x2`. Is that correct? (If it is, it is easily fixable in the sense of providing a better error message, but you need to specify something here that results in a by smooth being identified and then I can find the actual smooths pertaining to that by smooth.)

I was hoping for the call that lead to the `non-conformable arrays` error; I suspect it was something like

```r
difference_smooths(kurt_fin_aa_m2, smooth = "s(percent)")
```

and I can see why that might have issues as there are multiple smooths that look like `s(percent)` and `difference_smooths()` likely isn't clever enough to know what to do when you have a global and factor by smooth (`s(percent)` and `s(percent, by = x1x2)`). It may well also be picking up the the factor-smooth interaction smooths which also include `percent` though I thought my regexp was more specific than that...

**Comment by gavinsimpson** [comment]
Can you also install 0.7.3-18 (the development version from GitHub) and retry? Instructions on how to do this are in the [README](https://gavinsimpson.github.io/gratia/#installing-gratia). There have been a lot of changes under the hood, some of which might affect how I can reproduce your issue.
