### ISSUE TITLE
appraise fails for models with quasi family

### ISSUE THREAD

**Issue by sbrown-UniOfAdelaide** [gavinsimpson/gratia#19]
Currently `appraise` fails for models that have any of the `quasi` families specified

```
df <- gamSim(n = 400, verbose = TRUE, eg = 3)
Continuous `by' variable example
m <- gam(y ~ s(x1) + s(x2), data = df,
          family = quasi(link = "identity", variance = "constant"),
          method = "REML")
appraise(m) # FAILS
Error in qq_uniform(model, n = n_uniform, type = type) : 
  Quantile function for family <quasi> not available.
gam.check(m)

Method: REML   Optimizer: outer newton
full convergence after 7 iterations.
Gradient range [-1.290903e-08,5.530441e-09]
(score 528.3638 & scale 4.873964).
Hessian positive definite, eigenvalue range [0.3017501,198.5413].
Model rank =  19 / 19 

Basis dimension (k) checking results. Low p-value (k-index<1) may
indicate that k is too low, especially if edf is close to k'.

        k'  edf k-index p-value
s(x1) 9.00 1.94    1.00    0.56
s(x2) 9.00 6.61    1.05    0.86]
```

**Comment by gavinsimpson** [comment]
This is currently by design; we can't do the `direct randomisation` method for the QQ-plot without the quantile function of the family. We can't do the simulation method if we don't have a way to simulate data from the model. Neither of these are possible for the `quasi()` as `fix.family.qf()` and `fix.family.rd()` can't augment the `quasi()` family with the required functions.

You can achieve the same thing as `gam.check()` by using `appraise(m, method = 'normal')`, which uses the standard normal distribution for the theoretical quantiles on the QQ-plot.

`gam.check()` silently does this to you; which i don't like. My error message is not very helpful as it doesn't immediately suggest that you try something else for the `method` argument. I'll file a new issue to improve the error message to be more helpful.
