### ISSUE TITLE
`compute_partial_residuals` is wrong if deviance residuals are not equivalent to pearson residuals?

### ISSUE THREAD

**Issue by wStockhausen** [gavinsimpson/gratia#273]
Hope the following is helpful(!):

As I read the code, `compute_partial_residuals` pulls out residuals from a model object (`object` here) via `residuals(object)` and scales them by `sqrt(weights(object))`. For a `mgcv::gam` object, `residuals(object)` return the deviance residuals. I think scaling them by `sqrt(weights(object))` may not be the right thing to do in cases where deviance residuals are not equivalent to pearson residuals (e.g., when using the binomial family).

Note that `mgcv::plot.gam` with residuals=TRUE uses the *working residuals* to calculate partial residuals for its plots. The results can be quite different scale-wise from `draw(gam object, residuals=TRUE)` when the model family is non-gaussian (binomial in example below):
gratia draw.gam (it does look much nicer!)
![image](https://github.com/gavinsimpson/gratia/assets/5767668/e7eaaced-3224-4c19-802b-a36f6c6fc48c)
mgcv plot.gam
![image](https://github.com/gavinsimpson/gratia/assets/5767668/2de0d0bc-f5d6-4a11-b11f-f52be14da246)

(Took me some time to realize different *types* of residuals were being plotted). 

It might additionally be helpful to let the user specify the type of residuals returned by `compute_partial_residuals` via something like `type="working"` as an input (and as inputs to functions that call `compute_partial_residuals` like `draw.gam`). Probably the appropriate scaling would depend on the type of residuals requested.

**Comment by gavinsimpson** [comment]
Thanks for raising this issue @wStockhausen. I hadn't noticed that `plot.gam` was using the working residuals.

I would like to keep `draw.gam()` as close to `plot.gam()` as possible, so I don't plan to allow a choice of residuals, but if you have a convincing argument as to why this would be good, I can reconsider.

**Comment by wStockhausen** [comment]
Thanks Gavin! Your argument re choice of residuals makes sense.

*William T. Stockhausen*

Research Fishery Biologist, Alaska Fisheries Science Center

NOAA Fisheries | U.S. Department of Commerce

Office: (206) 526-4241

www.fisheries.noaa.gov

**Comment by emchuron** [comment]
Hi Gavin,

I just downloaded the latest version to try and deal with this issue, but it didn't seem to fix the issue with the residuals when using draw. When I went back into the code, it seems like the residuals are still being calculated using the sqrt(weights). Am I misunderstanding that this bug was supposed to fix this so that they were just calculated from the working residuals? I attached a screenshot showing the code I am looking at as well as where you can see the version of gratia installed on my computer.
<img width="1568" alt="Screenshot 2024-10-18 at 2 10 45 PM" src="https://github.com/user-attachments/assets/6b5820e6-2e0b-42a4-97eb-8b7b0a87b63c">

**Comment by gavinsimpson** [comment]
@emchuron The original bug was restricted to my using weighted deviance residuals when I should have been using weighted working residuals for compatibility with `mgcv::plot.gam`. The residuals do need to be weighted so multiplying them by `sqrt(weights)` is correct. By default the weights will all be `1` so this bit of code isn't going to change the working residuals at all. Only with user-supplied weights will the `sqrt(weights)` have any effect, but in that case the working residuals need to be weighted appropriately.

**Comment by emchuron** [comment]
ok. I was just wondering because I get very different results plotting residuals using the plot.gam function and the draw function. I have weights in my argument because my response is frequency of occurrence data (so a value from 0 - 1) and weights is the number of samples. It seems like if I reset my weights to 1 then my residuals will look like the ones coming from plot.gam. Thanks for the quick response

**Comment by gavinsimpson** [comment]
The only difference between what I am doing and what Simon does in `plot.mgcv` is that Simon takes the weights from the `model$weights` component (where `model` is your GAM), while I'm calling `weights()` to get the weights. I suspect that might be the course of any difference in this particular case where weights are using in a different sense from usual? I'll take a look at this further.

**Comment by emchuron** [comment]
That looks like it is probably the issue. The call weights() returns what is listed as the prior.weights in the model output, but Simon just directly references the weights output from the model, which looks like it is the same as the working weights?

**Comment by gavinsimpson** [comment]
Looks like I need `weights(model, type = "working")` instead.

**Comment by gavinsimpson** [comment]
@emchuron Thanks for following up on this. The issue is now fixed in the version on GitHub.
