### ISSUE TITLE
shift=TRUE not working for confint.gam()

### ISSUE THREAD

**Issue by TIMAVID** [gavinsimpson/gratia#280]
Hi,

I've tried to use confint() to create a confidence interval based on a GAM model, but when I've plotted the results the estimated values are shifted lower than I expect. I have specified "shift = TRUE" which should add a constant term from the model to make predictions on the right scale, but this seems to not be working for some reason.  

Thanks in advance for any help.

**Comment by TIMAVID** [comment]
This issue is not present when I revert to gratia version 0.8.1

**Comment by rbentham** [comment]
Hi,

I have also encountered this issue. I maintain a package that has a dependency on gratia (https://github.com/McGranahanLab/TcellExTRECT) besides the changing of the column names of confint.gam in 0.9.0 I am now getting different results compared to previous version. I have tested this and it is due to this issue of shift = TRUE not being functional within confint.gam from 0.9.0.

The code for confint.gam in gratia 0.8.2 included the following:

```
out[["est"]] <- ilink(out[["est"]] + const)
out[["lower"]] <- ilink(out[["lower"]] + const)
out[["upper"]] <- ilink(out[["upper"]] + const)
```
    
In gratia 0.9.0 this has changed to:
```
 out <- mutate(out, across(all_of(c(".estimate", ".lower_ci",
        ".upper_ci")), .fns = ilink))
```
With no reference to the const value and no shift in values even when shift = TRUE.  This could be easily fixed if you just replaced the above with something similar to the old version:

```
out[[".estimate"]] <- ilink(out[[".estimate"]] + const)
out[[".lower_ci"]] <- ilink(out[[".lower_ci"]] + const)
out[[".upper_ci"]] <- ilink(out[[".upper_ci"]] + const)
```

**Comment by gavinsimpson** [comment]
Yeah, sorry @TIMAVID and @rbentham; I messed that up. And sorry @TIMAVID for not getting to this sooner, even to acknowledge it (it's been a very busy month at work).

The problem is not in the lines of code you mention @rbentham but here https://github.com/gavinsimpson/gratia/blob/b03e7d55b2339a0888c6250773dd70c7c836a321/R/confint-methods.R#L417-L420

As far as I can tell, the `mutate()` call is doing what it is supposed to do, namely transform the using either the inverse link function, a user-supplied function, or the identity function, depending on what's passed to `transform`. I'm testing a fix now.

@rbentham Is this causing you problems with a package on CRAN? If so I can expedite a patch release to CRAN.

**Comment by gavinsimpson** [comment]
This is now fixed in the development version. I'm unlikely to get a version pushed to CRAN before middle of June unless it becomes very necessary for me to do so.

**Comment by rbentham** [comment]
@gavinsimpson Thanks for the quick response! My package is not on CRAN/Bioconductor which makes things a bit simpler to deal with. I am going to add this as a known issue to my package, and wait for the CRAN update to implement my fix to the confint.gam column names. Currently the change of column names results in an error to the relevant function so that the shift=TRUE issue does not even happen. When the latest version is out on CRAN I will add the fix and a new dependency to use the latest gratia version.
