### ISSUE TITLE
Difference between `data_slice %>% fitted_values` and `draw`?

### ISSUE THREAD

**Issue by GatesDupont** [gavinsimpson/gratia#316]
Hi,

I simulated some data and plotted the fitted relationship and partial residuals for the first covariate. I did this first manually, using `data_slice` and `fitted_values` from `gratia`. Then I did it using draw from gratia. The partial residuals are the same, but the smooth is different – the `draw` version has a lower smooth.

Here is a reproducible example:

```r
# Load the necessary library
library(tidyverse)
library(mgcv)
library(gratia)
library(cowplot)


# ---- Simulate data ----

set.seed(123)
n <- 200
x1 <- runif(n, 0, 10)
x2 <- runif(n, 0, 10)
x3 <- runif(n, 0, 10)
y <- sin(x1) + 0.5 * x2 + rnorm(n)


# ---- Fit data ----

# Fit a GAM with 3 covariates
model <- gam(y ~ s(x1) + s(x2) + s(x3), method = "REML")


# ---- Partial residuals ----

# Predict the smooth for the first covariate (x1) only
smooth_x1 <- predict(model, type = "terms", terms = "s(x1)")

# Calculate the residuals
residuals_model <- residuals(model)

# Calculate the partial residuals for x1
# Partial residuals = observed y - (fitted values excluding the smooth of x1) + smooth(x1)
fitted_values <- predict(model)
partial_residuals_x1 <- y - (fitted_values - smooth_x1[,1])


# ---- Organize data ----

df_partial.resids <- data.frame(x1r = x1, pr = partial_residuals_x1)

df_model.fitted <- data_slice(model, x1 = evenly(x1, 100), x2 = 0, x3 = 0) %>%
  fitted_values(model,., ci_level = 0.95)


# ---- Re-make gratia-style plot ----

p1 <- ggplot() +
  geom_point(data = df_partial.resids, aes(x = x1r, y = pr), color = "lightblue3") +
  geom_ribbon(data = df_model.fitted, aes(x = x1, y = .fitted, ymin = .lower_ci, ymax = .upper_ci), alpha = 0.2) +
  geom_line(data = df_model.fitted, aes(x = x1, y = .fitted)) +
  ylim(-3.5,3.5) +
  geom_hline(yintercept = c(-1,0,1), linetype = "dashed", color = 2) +
  theme(aspect.ratio = 5/7) +
  labs(x = "x1", y = "Partial effect", title = "s(x1) Done manually with data_slice and fitted_values", caption = "Basis: TPRS"); p1


# ---- Make gratia plot ----

p2 <- draw(model, select = 1, residuals = T, rug = F, ci_level = 0.95, 
     unconditional = F, overall_uncertainty = T) +
  geom_hline(yintercept = c(-1,0,1), linetype = "dashed", color = 2) +
  labs(title = "s(x) Done with gratia::draw") +
  theme(aspect.ratio = 5/7) +
  ylim(-3.5,3.5); p2


plot_grid(p1, p2)
```

Should I be doing something differently when I plot model-fitted relationships (using data_slice and fitted_values)? The `draw` version looks "better" to my eye, and I'm also just curious what the difference is.

Thank you!

![plot_zoom_png-1](https://github.com/user-attachments/assets/86e0948e-6c7f-471a-834b-96070beb3df1)

**Comment by gavinsimpson** [comment]
It's because the fitted values that you form using your `fitted_values` call contains the contributions for `x2` and `x3` when both are set to 0. I.e. the mean is shifted around a bit and there is additional uncertainty due to the uncertainty in the estimates of $f(x_2)$ and $f(x_3)$.

Setting the value of the covariate to 0 doesn't remove it's effect from the model. You need to set the value of the estimated function to be equal to 0. You do this by adding the `terms = "s(x1)"` that you used when you used `predict()` to form `smooth_x1`.

So things look the same if you change your script to use:

```r
df_model.fitted <- data_slice(model, x1 = evenly(x1, 100), x2 = 0, x3 = 0) %>%
  fitted_values(model, ., ci_level = 0.95, terms = "s(x1)")
```

FYI; to be consistent with what mgcv and hence gratia does, the working residuals should be used to create the partial residuals. It doesn't look like there's any difference here but in general the deviance residuals you used and working residuals won't be equal.

If you were trying to do things manually for some particular reason, you would be better off using `smooth_estimates()`. You could then add partial residuals as you are doing now etc. or just use `partial_residuals()`. `draw.gam()` uses `smooth_estimates()` under the hood so you will be getting everything it uses to plot smooths.

I say that, but I am not passing args on from `partial_residuals()` to the underlying `compute_partial_residuals()` function and hence `data` isn't being passed through in the code below.

```{r}
ds <- data_slice(model, x1 = evenly(x1))
sm <- smooth_estimates(model, select = "s(x1)", data = ds) |>
  mutate(presids = partial_residuals(model, select = "s(x1)", data = ds)) |> pull(`s(x1)`)
```

I will fix that

**Comment by GatesDupont** [comment]
Thanks for this! Very helpful. 

I see that `terms = "s(x1)"` in `fitted_values` gives me the same results as `draw`. Cool!

I'm trying to understand how this calculation works generally, even just from a simpler `lm` perspective. If including `terms = "s(x1)"` is removing the effect of the other covariates, could that similarly be achieved by zeroing out the x2 and x3 cells in a vcov matrix (along with zeroing out the coef estimates for x2 and x3)?

Like this, in a far simpler example obviously, but just to show sort of what I'm getting at:

```r
# Fit the linear model
model <- lm(y ~ x1 + x2)

# Extract the variance-covariance matrix
vcov_matrix <- vcov(model)

# Zero out x2-related variances and covariances
vcov_matrix_adj <- vcov_matrix
vcov_matrix_adj["x2", ] <- 0
vcov_matrix_adj[, "x2"] <- 0

# Set coefficient of x2 to zero
coef_adj <- coef(model)
coef_adj["x2"] <- 0

# Generate a new sequence of x1 values for which to compute fitted values and confidence intervals
x1_seq <- seq(min(x1), max(x1), length.out = 100)

# Create a new model matrix for these new x1 values (keeping intercept)
new_data <- data.frame(x1 = x1_seq, x2 = rep(0, length(x1_seq)))  # x2 is irrelevant and set to zero
new_model_matrix <- model.matrix(~ x1 + x2, data = new_data)

# Calculate fitted values using only x1 and intercept (ignoring x2)
fitted_values <- new_model_matrix %*% coef_adj

# Get the standard error for the fitted values (for x1 and intercept only)
se_fitted <- sqrt(diag(new_model_matrix %*% vcov_matrix_adj %*% t(new_model_matrix)))

# Calculate the 95% confidence intervals
lower_bound <- fitted_values - 1.96 * se_fitted
upper_bound <- fitted_values + 1.96 * se_fitted
```

Thanks!
