### ISSUE TITLE
gratia::derivatives: "Subscript out of bounds"-error on bs="fs" model

### ISSUE THREAD

**Issue by tomand-uio** [gavinsimpson/gratia#57]
I am trying to use hierarchical GAMs for analyzing microalgal growth curves in 96-well plates, so I fit a "S-type" GAM (cf. Pedersen et al. 2019) and want to extract derivatives to calculate growth rates. The following code shows an example that leads to the error message "Error in .subset2(x, i) : subscript out of bounds" when I try to apply derivatives() to the GAM object. 

I can imagine that one possible answer could be that this was never supposed to work, in which case I guess I'll use som combination of predict() and lapply() or similar produce rates of change for each unit. Or maybe I have just misunderstood something, and there is already a simple way to get this right? Or maybe it's an actual bug...

```r
logistic.growth <- function(t, y0, K, r) {
  return(K * (y0 / (y0 + (K - y0) * exp(-r * t))))
}

N <- 16
n <- 12

y0 <- 0.5
r  <- 0.25
K  <- rnorm(N, mean=5, sd=1)

d <- data.frame(
  unit=factor(rep(1:N, each=n)), 
  t=rep(seq(0, 20, length=n), N))
d$y <- logistic.growth(d$t, y0, K[d$unit], r)

S  <- 0.25
d$y.obs <- d$y + rnorm(nrow(d), sd=S)

library(mgcv)
library(gratia)

m <- gam(y.obs ~ s(t, unit, k=5, bs="fs", m=2), data=d, method="REML")
dm <- derivatives(m)
```

**Comment by gavinsimpson** [comment]
With your code I see this:

```
> dm <- derivatives(m)
Error in Summary.factor(c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L,  : 
  ‘min’ not meaningful for factors
```

with the current version on github (not CRAN). This is because an internal function used by `derivatives()` to generate data at which to compute the derivative is treating the spline as 2-d and trying to generate a sequence over the factor specified in the smooth.

So, yes, this is a bug.

**Comment by gavinsimpson** [comment]
Thanks for informing me about this @tomand-uio. I have now fixed this issue in the latest commit to the github version.

**Comment by tomand-uio** [comment]
?Dear Gavin,


Thank you for the swift and informative reply. I'm looking forward to an even better version of gratia with a solution to this. And thank you for your contributions to the R community and for continuing to write great papers (and a superb blog which I follow avidly)


Best regards,


  Tom

________________________________

**Comment by mahonmb** [comment]
Following up on this bug. I found a secondary issue with using `derivatives()` and a factor smooth, which appears when using linear covariates. Taking the example from above and adding a randomly generated variable as a linear covariate:

```
d$linearterm = runif(N)
m <- gam(y.obs ~ s(t, unit, k=5, bs="fs", m=2) + linearterm, data=d, method="REML")
dm <- derivatives(m)
```
This returns the following error: 

```
> dm <- derivatives(m)
Error in `str_detect()`:
! Can't recycle `string` (size 2) to match `pattern` (size 3).
```

I think the issue comes from `stringr::str_detect(smooth_vars, m_vars)` within the helper `derivatives_data()`.

**Comment by gavinsimpson** [comment]
@mahonmb Confirmed in my latest GitHub version. Will start a new issue for this.

**Comment by gavinsimpson** [comment]
Thanks for the report @mahonmb; this is now fixed in the GH version

**Comment by mahonmb** [comment]
Thanks, @gavinsimpson! Looking forward to using it.
