### ISSUE TITLE
Necessary to require R Version > 3.6.0?

### ISSUE THREAD

**Issue by jflournoy** [gavinsimpson/gratia#78]
I'm working on a computing system that only has R 3.5.1 installed and so am installing a version of this package prior to the increase in required R version. Are there particular parts of the package that you know will break under 3.5?

**Comment by gavinsimpson** [comment]
I wouldn't do that; there's been a lot of errors and bugs fixed since I switched to requiring the 3.6.0 branch. I don't think the code itself needs >= 3.6.0 but I didn't want to have to deal with the change in the RNG that came in with the 3.6 branch of R as well as the older versions of R as is required by CRAN. You might try forking the repo and removing the R dependency from the `DESCRIPTION` file, and then use `remotes::install_github()` to install from your fork.

**Comment by jflournoy** [comment]
Thank you understanding the point of the question, and for the helpful advice. I'll do as you suggest.
