### ISSUE TITLE
confint() not running

### ISSUE THREAD

**Issue by butellyn** [gavinsimpson/gratia#80]
When I try to run confint on a gamm4 object generated using the following commands:
```
mod <- gamm4(test ~ s(Age, by=factor_var, k=60, bs="cr") +
    s(Age, k=40, bs="cr"), data=data_df, random=~(1|subject), REML=TRUE)

CI <- confint(mod$gam, parm='s(Age):factor_level1', type='confidence')
```
I get the following warning messages, and an empty tibble: "Warnings messages: 1: Unknown or uninitialised column: `est`. 2. Unknown or  uninitialised column: `crit`. 3. Unknown or  uninitialised column: `se`. 4: Unknown or uninitialised column: `est`. 5. Unknown or  uninitialised column: `crit`. 6. Unknown or  uninitialised column: `se`."

Then, I took a look at the code for the function: https://github.com/gavinsimpson/gratia/blob/master/R/confint-methods.R

I had to manually load the package `qdap` to get the add_s() function to work, and which_smooth() could not be found (line 246). I wonder if this is supposed to be which_smooths()? At this point, I stopped, because I either have done something really funky or there are some bugs in this code. 

Thanks for taking a look!

**Comment by gavinsimpson** [comment]
This should now be fixed in the version on @master.

This was partly related to how I was matching smooth labels.

The reason your explorations weren't working is that `add_s()` and `which_smooth()` are internal functions not exported from the package. You would need to preface them with `gratia:::` to refer to them by name like this.
